name: 'Dynamic Action'
description: 'Dynamically use an action based on environment variables'
inputs:
  repository:
    description: 'Name of the repository'
    default: ${{ github.repository }}
    required: false
  branch:
    description: 'Branch name'
    default: ${{ github.ref_name }}
    required: false
  version:
    description: "Ballerina Version"
    required: true
    default: 2201.9.2
runs:
  using: "composite"
  steps:
    - uses: ${{ inputs.repository }}@${{ inputs.branch }}
      with:
        version: ${{ inputs.version }}

